export const INDIAN_STATES_AND_DISTRICTS: Record<string, string[]> = {
    "andhra pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Rajahmundry", "Tirupati"],
    "arunachal pradesh": ["Itanagar", "Tawang", "Ziro", "Pasighat"],
    "assam": ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon", "Tinsukia"],
    "bihar": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia", "Darbhanga"],
    "chhattisgarh": ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg"],
    "goa": ["North Goa", "South Goa", "Panaji", "Margao"],
    "gujarat": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhinagar"],
    "haryana": ["Gurugram", "Faridabad", "Panipat", "Ambala", "Karnal", "Hisar"],
    "himachal pradesh": ["Shimla", "Manali", "Dharamshala", "Mandi", "Solan"],
    "jharkhand": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Hazaribagh"],
    "karnataka": ["Bengaluru", "Mysuru", "Mangaluru", "Hubballi-Dharwad", "Belagavi", "Gulbarga"],
    "kerala": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kannur", "Kollam"],
    "madhya pradesh": ["Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain"],
    "maharashtra": ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik", "Aurangabad", "Solapur", "Amravati", "Navi Mumbai"],
    "manipur": ["Imphal", "Thoubal", "Bishnupur"],
    "meghalaya": ["Shillong", "Tura", "Jowai"],
    "mizoram": ["Aizawl", "Lunglei", "Champhai"],
    "nagaland": ["Kohima", "Dimapur", "Mokokchung"],
    "odisha": ["Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur", "Puri"],
    "punjab": ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali"],
    "rajasthan": ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Bikaner", "Ajmer"],
    "sikkim": ["Gangtok", "Namchi", "Gyalshing"],
    "tamil nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli"],
    "telangana": ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam"],
    "tripura": ["Agartala", "Udaipur", "Dharmanagar"],
    "uttar pradesh": ["Lucknow", "Kanpur", "Ghaziabad", "Agra", "Varanasi", "Meerut", "Prayagraj", "Noida"],
    "uttarakhand": ["Dehradun", "Haridwar", "Roorkee", "Haldwani", "Nainital"],
    "west bengal": ["Kolkata", "Howrah", "Durgapur", "Asansol", "Siliguri", "Darjeeling"],
    "delhi": ["New Delhi", "North Delhi", "South Delhi", "East Delhi", "West Delhi", "Central Delhi"],
    "chandigarh": ["Chandigarh"],
    "puducherry": ["Puducherry", "Karaikal", "Mahe", "Yanam"]
};

export const SPECIALIZATIONS = [
    'Criminal Defense',
    'Civil Litigation',
    'Family Law',
    'Corporate Law',
    'Property & Real Estate',
    'Startups & Business',
    'Cyber Crime',
    'Labor & Employment',
    'Intellectual Property',
    'Immigration',
    'Taxation'
];
